theme = "monokai_pro"

[editor]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "Normal"
mode.insert = "Insert"
mode.select = "Extend"

[editor.lsp]
display-inlay-hints = true

